const tokenList = [
    {
      tokenName:"client_ip",
      description:'The mobile IP address when conversion happened.'
    },
    {
      tokenName:"carrier",
      description:'The carrier name of the mobile when conversion happened.'
    },
    {
      tokenName:"android_id",
      description:'For Android devices only.'
    },
    {
      tokenName:"device_id",
      description:'General device id to support multiple device type.'
    },
    {
      tokenName:"idfa",
      description:"Apple's advertiser identifier with iOS 6+"
    },
    {
      tokenName:"google_adv_id",
      description:'Google\'s advertising identifier.'
    },
    {
      tokenName:"mac",
      description:'MAC address of the phone\'s wifi adapter.'
    },
    {
      tokenName:"imei",
      description:'IMEI number of the mobile device.'
    },
    {
      tokenName:"active_time",
      description:'Active time of the conversion, such as install time.'
    },
    {
      tokenName:"oid",
      description:'The unique ID generated by advertiser for each conversion.'
    },
    {
      tokenName:"adv_sub",
      description:'Advertiser sub specified in the conversion pixel.'
    },
    {
      tokenName:"adv_sub2",
      description:'Advertiser sub 2 specified in the conversion pixel.'
    },
    {
      tokenName:"adv_sub3",
      description:'Advertiser sub 3 specified in the conversion pixel.'
    },
    {
      tokenName:"adv_sub4",
      description:'Advertiser sub 4 specified in the conversion pixel.'
    },
    {
      tokenName:"adv_sub5",
      description:'Advertiser sub 5 specified in the conversion pixel.'
    },
    {
      tokenName:"adv_sub6",
      description:'Advertiser sub 6 specified in the conversion pixel.'
    },
    {
      tokenName:"adv_sub7",
      description:'Advertiser sub 7 specified in the conversion pixel.'
    },
    {
      tokenName:"adv_sub8",
      description:'Advertiser sub 8 specified in the conversion pixel.'
    },
]

const basicHelpTips = {
    offer_type: 'Set offer type here.</br>Notice: For CPE offer, am should set offer type as CPI if adv will only fire post back for event.',
    publisher_white_black_list: 'Setting publisher black list here, white list is unavailable by now.',
    offer_url: 'Tracking link of campaign that provided by adv to track click data and redirect to download page.',
    check_redirect_pattern: 'Check it when choose S2S pattern to integrate with adv, Check the instructor S2S integration guide（ADV）to learn more details about S2S pattern.',
    notification_url: 'When S2S is chosen, notification url is required to place.',
    preview_link: 'The final download page, provided by adv or copied from webpage.',
    tracking_system: 'Choose the tracking system that adv using.',
    conversion_pixel: 'Here to record the conversion post back link that adv using.</br>Notice: recording only and won’t take a real effect.',
    permission: 'Set the level of affiliate, this level will determine affiliate access to offers. From table below to learn more about the detailed mapping table between affiliate level and offer level.</br>' +
        '<table class="table">' +
            '<thead>'+
                '<tr>' +
                    '<th> Offer level</th>' +
                    '<th> Affiliate access</th>' +
                '</tr>'+
            '</thead>'+
            '<tbody>'+
                '<tr>'+
                    '<td> Public </td>'+
                    '<td> Available to all publisher levels by default</td>'+
                '</tr>'+
                '<tr>'+
                    '<td> Public (Require Approval)</td>'+
                    '<td> Available to level3&level2 affiliate by default. level1 affiliate need to answer questions am set as application firstly, and will have the permission to run only after PM approved in Offer Applications page.</td>'+
                '</tr>'+
                '<tr>'+
                    '<td> Private</td>'+
                    '<td> Available to level3 affiliate by default. For level1&level2 affiliate need to be approved.</td>'+
                '</tr>'+
            '</tbody></table>',
    offer_action: '1.  Do nothing: System won’t change offer’s status after offer budget is exhausted.</br>2.  Suspend offer: System will change offer’s status from active to suspend after offer budget is exhausted. </br>3.  Renew: System will extend the expiration date of active offers for one week/month after offer budget is exhausted.',
    exclusive: 'Set to YES when it’s an exclusive offer to Yeahmobi.',
    incentive: 'To mark whether incentive traffic is allowed to this offer.',
    allowed_traffic: 'To mark what kind of traffic is allowed.',
    conversion_flow: 'To define what action is count as a paid conversion flow for this offer.'
}
const affiliateAccessHelpTips = {
  affiliate_access: 'Affiliates in approved list are able to run this offer only.</br>Notice：</br>•  Offers created by api are available to devapp publishers only.</br>•  the priority for offer access :For specific affiliate in offer page > publisher page & adv page'
}
const appAccessHelpTips = {
  app_access: 'Affiliates in approved list are able to run this offer only.</br>Notice：</br>•  To block/approve the specific app for devapp publisher. </br>•  the priority for offer access :For specific app in offer page > publisher page & adv page'
}
const offerHelpTips = {
  exclude_from_mana: 'Default No. When am set it to YES, means block devapp publisher to this offer automatically, unless devapp publisher is approved to this offer manually.'
}
const paymentHelpTips = {
  payment: 'Generally, there are two kind of payment modes: Fixed revenue & Dynamic revenue. And USD is the only currency that our system support.</br>1. Fixed revenue：Dynamic Revenue set as NO.</br>•  Revenue per Conversion: the value here will be same for every conversion.</br>• Payout per Conversion: payout here will be a fixed value for every conversion if revenue is fixed. </br>2.  Dynamic revenue: Dynamic Revenue set as YES</br>•   Revenue per Conversion: the real revenue depends on the {revenue} in Conversion Pixel that adv fried for every conversion. The value here will take effect when adv didn’t post back (revenue) to us.</br>• Payout per Conversion: Here to set a proportion of dynamic revenue as payout.',
  na: 'Here to set an individual payout and cap for specific affiliate.</br>Notice: the priority for CC and cap.</br>For specific affiliate in offer page > publisher page > payment in offer page',
  pa: 'Here to set an individual payout and cap for specific devapp publisher.</br>Notice: the priority for CC and cap.</br>• CC: specific affiliate in offer page > publisher page > payment in offer page.</br>•    Cap: specific affiliate in offer page >app info in publisher page > payment in offer page'
}
const targetingHelpTips = {
 geo_targeting: 'Select the target Geo for this offer.</br>Notice: </br>•  Supporting target city.</br>•  Clicks outside of the target geo will be rejected in YM system.',
 platform_targeting: 'Select the target platform for this offer. </br>Notice: clicks outside of the target platform will be rejected in YM system.',
 device_os_targeting: 'Select the target device OS for this offer.</br>Notice: clicks outside of the target device OS will be rejected in YM system.',
 device_model_targeting: 'Select the target Device Model for this offer.</br>Notice:</br>•  Clicks outside of the target Device Model will be rejected in YM system.</br>•  YM system cannot distinguish device model of the click data correctly, so we suggest you do not open this setting.',
 carriers: "Select the target carriers for this offer.</br>Notice: 'carrier' token will be required to post back when this option is set to YES."

}
const trackingHelpTips = {
  tracking_domain: 'Set an individual tracking domain for a specific publisher.</br>Notice: to avoid the risk that ‘’https://global.ymtracking.com/’’ is banned, please choose a domain that belong to adv or affiliate in here for DDL offer.',
  tracking_link: 'Used for tracking click and redirect. YM system will generate a unique tracking link for every approved affiliate. </br>Notice: for devapp publisher please go to api feed to get the tracking link.',
  independent_domain: 'Set an independent domain of offer url for specific publisher.</br>Notice: to avoid the risk that offer url is banned please use independent domain.',
  global_pixel_type: 'Simple：Default mode, use postback Pixel as the post back url for this affiliate.</br>Advanced: Choose this mode to post back conversions to affiliate when micro that required are not in token list. Pixel Url, Request Methods and Headers should be provided by affiliate side.',
  postback_pixel: 'Affiliate’s post back link for this offer.',
  html_pixel: 'Set affiliate post back in HTML format according to affiliate requirement. It should be provided by affiliate.',
  advertiser_conversion_white_list: 'Here to show the Conversion White List that set in adv page.',
  offer_conversion_white_list: 'Set Conversion White List at offer level. Conversion which ip is not in the white list will be rejected in system.'
}

const values = ['Now','After 12 hours','After 24 hours','After 48 hours','Customized time']
const keys1 = ['now+','later+12','later+24','later+48','custom']
const keys2 = ['-1','12','24','48','customized']
const effectiveTime1 = () => {
  let effectiveTime = []
  keys1.forEach(function (value,index) {
    effectiveTime.push({
      key:value,
      value:values[index]
    })
  });
  return effectiveTime
}
const effectiveTime2 = () => {
  let effectiveTime = []
  keys2.forEach(function (value,index) {
    effectiveTime.push({
      key:value,
      value:values[index]
    })
  });
  return effectiveTime
}

const defaultKpiNameList = {
    cr: {
      label: 'CR',
      value: 'cr',
      event_name: 'gt_cr',
      canSetOnAutoBlendTraffic:true,
    },
    click_hijacking: {
      label: 'Click Injection',
      value: 'click_hijacking',
      event_name: 'lt_ctit',
      tmp: 'Click Injection </br> Max CTIT: 10s',
      canSetOnAutoBlendTraffic:true,
    },
    click_flood: {
      label: 'Click Flood',
      value: 'click_flood',
      event_name: 'gt_ctit',
      tmp: 'Click Flood </br> Min CTIT: 3600s',
      canSetOnAutoBlendTraffic:true,
    },
    retention: {
      label: 'Retention Rate',
      value: 'retention',
      event_name: 'retention',
      canSetOnAutoBlendTraffic:true,
      tmp: 'Retention Rate </br> Day {{event_param}}',
      days:[
        {
          key:1,
          label:'Day 1'
        },
        {
          key:2,
          label:'Day 2'
        },
        {
          key:3,
          label:'Day 3'
        },
        {
          key:4,
          label:'Day 4'
        },
        {
          key:5,
          label:'Day 5'
        },
        {
          key:6,
          label:'Day 6'
        },
        {
          key:7,
          label:'Day 7'
        },
        {
          key:30,
          label:'Day 30'
        }
      ]
    },
    abnormal_ip: {
      label: 'Abnormal IP',
      value: 'abnormal_ip',
      event_name: 'abnormal_ip',
    },
    cdr: {
      label: 'CDR',
      value: 'cdr',
      event_name: 'cdr',
    },
    cdi: {
      label: 'CDI',
      value: 'cdi',
      event_name: 'cdi',
    },
    out_of_store: {
      label: 'Out of Store',
      value: 'out_of_store',
      event_name: 'out_of_store',
    },
    monthly_roi: {
      label: 'Monthly ROI',
      value: 'monthly_roi',
      event_name: 'monthly_roi',
      canSetOnAutoBlendTraffic:true,
    },
    lv3:{
      canSetOnAutoBlendTraffic:true,
      label: 'Level 3 Rate',
      value: 'lv3',
      event_name:'lv3'
    },
    register:{
      canSetOnAutoBlendTraffic:true,
      value: 'register',
      label: 'Register',
      event_name:'register'
    }
}
const mergeKpiSettingName = (defaultValue, prop) => {
    let result = {}
    prop.map(item => {
        if (Object.keys(defaultValue).includes(item)) {
            return
        }
        result[item] = {
            value: item,
            label: item.replace(/\_/g, ' ').replace(/\b[a-z]/g, char => char.toUpperCase()),
            event_name: item,
            canSetOnAutoBlendTraffic:true, //系统配置的kpi都可以在自动混量组合进行删选和配置
        }
    })
    return Object.assign(defaultValue, result)
}
export { tokenList, basicHelpTips, affiliateAccessHelpTips, appAccessHelpTips, offerHelpTips, targetingHelpTips, trackingHelpTips, paymentHelpTips, effectiveTime1, effectiveTime2,defaultKpiNameList,mergeKpiSettingName };